export const SEMANTIC_BONES = [
  "hips",
  "spine",
  "spineMiddle",
  "spineUpper",
  "chest",
  "neck",
  "neckUpper",
  "head",
  "leftShoulder",
  "leftUpperArm",
  "leftUpperArmMiddle",
  "leftForearm",
  "leftForearmMiddle",
  "leftHand",
  "rightShoulder",
  "rightUpperArm",
  "rightUpperArmMiddle",
  "rightForearm",
  "rightForearmMiddle",
  "rightHand",
  "leftUpperLeg",
  "leftUpperLegMiddle",
  "leftLowerLeg",
  "leftFoot",
  "rightUpperLeg",
  "rightUpperLegMiddle",
  "rightLowerLeg",
  "rightFoot",
] as const;

export type SemanticBone = (typeof SEMANTIC_BONES)[number];

// Keep runtime control intentionally small. The FV2.1 helper/intermediate bones
// inherit these rotations through the rig hierarchy and remain at bind-local
// transforms instead of receiving duplicate tracking deltas.
export const DIRECTLY_CONTROLLED_BONES = [
  "hips",
  "spine",
  "neck",
  "head",
  "leftUpperArm",
  "leftForearm",
  "rightUpperArm",
  "rightForearm",
  "leftUpperLeg",
  "leftLowerLeg",
  "rightUpperLeg",
  "rightLowerLeg",
] as const satisfies readonly SemanticBone[];

export const BONE_ALIASES: Record<SemanticBone, readonly string[]> = {
  hips: ["Hips", "Pelvis", "Root", "mixamorigHips"],
  spine: ["Spine", "mixamorigSpine"],
  spineMiddle: ["Spine1", "Spine_1"],
  spineUpper: ["Spine2", "Spine_2", "mixamorigSpine1"],
  chest: ["Chest", "UpperChest", "Spine3", "mixamorigSpine2"],
  neck: ["Neck", "mixamorigNeck"],
  neckUpper: ["Neck1", "Neck_1", "UpperNeck"],
  head: ["Head", "mixamorigHead"],
  leftShoulder: ["Left_Shoulder", "LeftShoulder", "mixamorigLeftShoulder"],
  leftUpperArm: ["Left_Arm", "LeftArm", "LeftUpperArm", "mixamorigLeftArm"],
  leftUpperArmMiddle: ["Left_Arm_middle", "LeftArmMiddle", "Left_Arm_Middle"],
  leftForearm: ["Left_ForeArm", "LeftForeArm", "LeftLowerArm", "mixamorigLeftForeArm"],
  leftForearmMiddle: ["Left_ForeArm_middie", "Left_ForeArm_middle", "LeftForeArmMiddle"],
  leftHand: ["Left_Hand", "LeftHand", "mixamorigLeftHand"],
  rightShoulder: ["Right_Shoulder", "RightShoulder", "mixamorigRightShoulder"],
  rightUpperArm: ["Right_Arm", "RightArm", "RightUpperArm", "mixamorigRightArm"],
  rightUpperArmMiddle: ["Right_Arm_middle", "RightArmMiddle", "Right_Arm_Middle"],
  rightForearm: ["Right_ForeArm", "RightForeArm", "RightLowerArm", "mixamorigRightForeArm"],
  rightForearmMiddle: ["Right_ForeArm_middie", "Right_ForeArm_middle", "RightForeArmMiddle"],
  rightHand: ["Right_Hand", "RightHand", "mixamorigRightHand"],
  leftUpperLeg: ["Left_UpperLeg", "LeftUpLeg", "LeftThigh", "mixamorigLeftUpLeg"],
  leftUpperLegMiddle: ["Left_thigh1", "LeftThigh1", "Left_Thigh1"],
  leftLowerLeg: ["Left_LowerLeg", "LeftLeg", "LeftShin", "mixamorigLeftLeg"],
  leftFoot: ["Left_Foot", "LeftFoot", "mixamorigLeftFoot"],
  rightUpperLeg: ["Right_UpperLeg", "RightUpLeg", "RightThigh", "mixamorigRightUpLeg"],
  rightUpperLegMiddle: ["Right_thigh1", "RightThigh1", "Right_Thigh1"],
  rightLowerLeg: ["Right_LowerLeg", "RightLeg", "RightShin", "mixamorigRightLeg"],
  rightFoot: ["Right_Foot", "RightFoot", "mixamorigRightFoot"],
};

// Canonical FV2.1 mannequin hierarchy. Future garment GLBs are expected to retain
// these avatar bone names while clothing geometry and materials may change.
export const MANUAL_BONE_MAP: Partial<Record<SemanticBone, string>> = {
  hips: "Pelvis",
  spine: "Spine",
  spineMiddle: "Spine1",
  spineUpper: "Spine2",
  chest: "Spine3",
  neck: "Neck",
  neckUpper: "Neck1",
  head: "Head",
  leftShoulder: "Left_Shoulder",
  leftUpperArm: "Left_Arm",
  leftUpperArmMiddle: "Left_Arm_middle",
  leftForearm: "Left_ForeArm",
  leftForearmMiddle: "Left_ForeArm_middie",
  leftHand: "Left_Hand",
  rightShoulder: "Right_Shoulder",
  rightUpperArm: "Right_Arm",
  rightUpperArmMiddle: "Right_Arm_middle",
  rightForearm: "Right_ForeArm",
  rightForearmMiddle: "Right_ForeArm_middie",
  rightHand: "Right_Hand",
  leftUpperLeg: "Left_thigh",
  leftUpperLegMiddle: "Left_thigh1",
  leftLowerLeg: "Left_shin",
  leftFoot: "Left_ankle",
  rightUpperLeg: "Right_thigh",
  rightUpperLegMiddle: "Right_thigh1",
  rightLowerLeg: "Right_shin",
  rightFoot: "Right_ankle",
};

export const REQUIRED_MOTION_BONES: readonly SemanticBone[] = [
  "hips",
  "leftUpperArm",
  "leftForearm",
  "rightUpperArm",
  "rightForearm",
  "leftUpperLeg",
  "leftLowerLeg",
  "rightUpperLeg",
  "rightLowerLeg",
];
