export const SEMANTIC_BONES = [
  "hips",
  "spine",
  "chest",
  "neck",
  "head",
  "leftShoulder",
  "leftUpperArm",
  "leftForearm",
  "leftHand",
  "rightShoulder",
  "rightUpperArm",
  "rightForearm",
  "rightHand",
  "leftUpperLeg",
  "leftLowerLeg",
  "leftFoot",
  "rightUpperLeg",
  "rightLowerLeg",
  "rightFoot",
] as const;

export type SemanticBone = (typeof SEMANTIC_BONES)[number];

export const BONE_ALIASES: Record<SemanticBone, readonly string[]> = {
  hips: ["Hips", "Pelvis", "Root", "mixamorigHips"],
  spine: ["Spine", "Spine1", "mixamorigSpine"],
  chest: ["Chest", "UpperChest", "Spine2", "mixamorigSpine1", "mixamorigSpine2"],
  neck: ["Neck", "mixamorigNeck"],
  head: ["Head", "mixamorigHead"],
  leftShoulder: ["Left_Shoulder", "LeftShoulder", "mixamorigLeftShoulder"],
  leftUpperArm: ["Left_Arm", "LeftArm", "LeftUpperArm", "mixamorigLeftArm"],
  leftForearm: ["Left_ForeArm", "LeftForeArm", "LeftLowerArm", "mixamorigLeftForeArm"],
  leftHand: ["Left_Hand", "LeftHand", "mixamorigLeftHand"],
  rightShoulder: ["Right_Shoulder", "RightShoulder", "mixamorigRightShoulder"],
  rightUpperArm: ["Right_Arm", "RightArm", "RightUpperArm", "mixamorigRightArm"],
  rightForearm: ["Right_ForeArm", "RightForeArm", "RightLowerArm", "mixamorigRightForeArm"],
  rightHand: ["Right_Hand", "RightHand", "mixamorigRightHand"],
  leftUpperLeg: ["Left_UpperLeg", "LeftUpLeg", "LeftThigh", "mixamorigLeftUpLeg"],
  leftLowerLeg: ["Left_LowerLeg", "LeftLeg", "LeftShin", "mixamorigLeftLeg"],
  leftFoot: ["Left_Foot", "LeftFoot", "mixamorigLeftFoot"],
  rightUpperLeg: ["Right_UpperLeg", "RightUpLeg", "RightThigh", "mixamorigRightUpLeg"],
  rightLowerLeg: ["Right_LowerLeg", "RightLeg", "RightShin", "mixamorigRightLeg"],
  rightFoot: ["Right_Foot", "RightFoot", "mixamorigRightFoot"],
};

// Canonical FV2.1 mannequin hierarchy. Future garment GLBs are expected to retain
// these avatar bone names while clothing geometry and materials may change.
export const MANUAL_BONE_MAP: Partial<Record<SemanticBone, string>> = {
  hips: "Pelvis",
  spine: "Spine",
  chest: "Spine3",
  neck: "Neck",
  head: "Head",
  leftShoulder: "Left_Shoulder",
  leftUpperArm: "Left_Arm",
  leftForearm: "Left_ForeArm",
  leftHand: "Left_Hand",
  rightShoulder: "Right_Shoulder",
  rightUpperArm: "Right_Arm",
  rightForearm: "Right_ForeArm",
  rightHand: "Right_Hand",
  leftUpperLeg: "Left_thigh",
  leftLowerLeg: "Left_shin",
  leftFoot: "Left_ankle",
  rightUpperLeg: "Right_thigh",
  rightLowerLeg: "Right_shin",
  rightFoot: "Right_ankle",
};

export const REQUIRED_MOTION_BONES: readonly SemanticBone[] = [
  "hips",
  "leftUpperArm",
  "leftForearm",
  "rightUpperArm",
  "rightForearm",
  "leftUpperLeg",
  "leftLowerLeg",
  "rightUpperLeg",
  "rightLowerLeg",
];
